### ISSUE TITLE
Handle Docker Hub

### ISSUE THREAD

**Issue by flavio** [kubewarden/policy-fetcher#19]
It is true that right now Docker Hub doesn't support OCI artifacts, however... our code would fail when a user attempts to interact with the docker hub under certain circumstances.

This would happen because in many places of our code we rely on the `url` crate to understand whether a policy is located on a http(s), file or registry location.

See the following gist about how things can go wrong under certain circumstances: https://gist.github.com/flavio/7f60b12791b3de111f942896756fa24c

**Comment by ereslibre** [comment]
What do you think is the best approach?

In the context of one of the provided examples, `registry://flavio/awesome-stuff:v0.1.0`, `flavio` is a valid host and I think is reasonable to treat it like so. I don't think we should provide any special logic to be smart about the Docker Hub.

In the future, when the Docker Hub supports OCI artifacts, I think it's reasonable to ask for the user to refer to them as `registry://registry.hub.docker.com/...` or a path host+path that will serve this purpose.

I understand the defaulting logic at the docker+podman image container level, but I don't think we should implement anything like that.

Unless I misunderstood something I would close this issue as invalid.

**Comment by ereslibre** [comment]
I don't think we should allow `registry://busybox:v0.1.0`, this is not a well formed URL becauase `v0.1.0` is not a valid port.

I think we should only allow valid URL's (always with a host, and optionally with a port).

**Comment by flavio** [comment]
The problem is that `docker pull busybox:v0.1.0` is a valid reference. This is a bit extreme, I know... because I don't expect wasm policies to be stored as top level objects into the docker hub.

Because of that I think we can close it
