### ISSUE TITLE
Support pulling from endpoints secured with self-signed certificates

### ISSUE THREAD

**Issue by flavio** [kubewarden/policy-fetcher#3]
We should provide a way to allow users to fetch policies from an endpoint (be it `https://` or `registry://`) that is secured with a self-signed certificate.

This will be doable once the oci-crate has a new  release that includes https://github.com/deislabs/krustlet/pull/521

**Comment by flavio** [comment]
@ereslibre I think this can be closed as done, am I right?

**Comment by ereslibre** [comment]
Yes, this is fully implemented! 🎉
